[global]
repo1-type=s3
repo1-s3-region=auto
repo1-s3-uri-style=path
repo1-retention-full=2
spool-path=/var/lib/pgbackrest

[main]
pg1-path=/var/lib/postgresql/data
pg1-user=app
pg1-socket-path=/var/run/postgresql

