# Generated by Django 6.0.5 on 2026-05-25 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_budget_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(max_length=500)),
                ('note', models.TextField(blank=True)),
                ('from_account', models.CharField(blank=True, max_length=64)),
                ('to_account', models.CharField(blank=True, max_length=64)),
                ('counterparty', models.CharField(blank=True, max_length=200)),
                ('external_id', models.CharField(max_length=100)),
                ('raw', models.JSONField(blank=True, default=list)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.household')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('household', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TransactionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='splits', to='finance.category')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='finance.transaction')),
            ],
        ),
    ]
