# Generated by Django 6.0.5 on 2026-05-27 20:07

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_transaction_transactionsplit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='As it appears in the bank CSV.', max_length=64)),
                ('label', models.CharField(blank=True, max_length=100)),
                ('tracked', models.BooleanField(default=True, help_text='One of our own accounts — include in balances and net worth.')),
                ('opening_balance', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Balance as of the opening date (or all-time if no date).', max_digits=12)),
                ('opening_date', models.DateField(blank=True, help_text='Date the opening balance applies to; flows on/after it accrue.', null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='finance.household')),
            ],
            options={
                'ordering': ['sort_order', 'label', 'number'],
                'unique_together': {('household', 'number')},
            },
        ),
    ]
